ENT.Type = "anim"
ENT.Base = "base_anim"
ENT.PrintName	= "Shuttle"
ENT.Author	= "Catdaemon"
ENT.Contact	= ""
ENT.Purpose	= ""
ENT.Instructions= ""
ENT.Spawnable	= false
ENT.AdminSpawnable = false